### ISSUE TITLE
define声明调用失败

### ISSUE THREAD

**Issue by guodf** [zhangyuang/node-ffi-rs#77]
## Current ffi-rs version
` "ffi-rs": "^1.0.95"`
Print current Node.js info with the following code

`v20.12.0`

$ cat node_modules/ffi-rs/package.json

```json
{
  "name": "test",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "description": "",
  "dependencies": {
    "@yuuang/ffi-rs-win32-x64-msvc": "^1.0.95",
    "ffi-rs": "^1.0.95"
  }
}
```

$ ls node_modules/@yuuang

![image](https://github.com/user-attachments/assets/92ee49ac-1abb-43b8-9d0a-e363799e1dbd)

## Current Node.js arch

`x64 win32`

$ node -e "console.log(process.arch, process.platform)"

## Descibe your problem in detail

```shell
G:\test\node_modules\ffi-rs\index.js:351
  return load(processParamsTypeForArray(params))
         ^

Error: Missing field `paramsValue`
    at wrapLoad (G:\test\node_modules\ffi-rs\index.js:351:10)
    at res.<computed> [as Hello] (G:\test\node_modules\ffi-rs\index.js:369:38)      
    at Object.<anonymous> (G:\test\test.js:20:5)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'InvalidArg'
}
```

## 我的测试代码
[test.zip](https://github.com/user-attachments/files/17089337/test.zip)

```shell
PS G:\test> gcc -v
Using built-in specs.
COLLECT_GCC=D:\mingw64\bin\gcc.exe
COLLECT_LTO_WRAPPER=C:/vhd/d/mingw64/bin/../libexec/gcc/x86_64-w64-mingw32/13.2.0/lto-wrapper.exe
OFFLOAD_TARGET_NAMES=nvptx-none
Target: x86_64-w64-mingw32
Configured with: ../configure --prefix=/R/winlibs64ucrt_stage/inst_gcc-13.2.0/share/gcc --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --enable-offload-targets=nvptx-none --with-pkgversion='MinGW-W64 x86_64-ucrt-posix-seh, built by Brs --disable-stage1-checking --disable-win32-registry --disable-multilib --enable-ld --enable-libquadmath --enable-libada --enable-libssp --enable-libstdcxx --enable-lto --enable-fully-dynamic-string --enable-libgomp --enable-graphite --enable-mingw-wildcard --enable-libstdcxx-time --enable-libstdcxx-pch --with-mpc=/d/Prog/winlibs64ucrt_stage/custombuilt --with-mpfr=/d/Prog/winlibs64ucrt_stage/custombuilt --with-gmp=/d/Prog/winlibs64ucrt_stage/custombuilt --with-isl=/d/Prog/winlibs64ucrt_stage/custombuilt --disable-libstdcxx-backtrace --enable-install-libiberty --enable-__cxa_atexit --without-included-gettext --with-diagnostics-color=auto --enable-clocale=generic --with-libiconv --with-system-zlib --with-build-sysroot=/R/winlibs64ucrt_stage/gcc-13.2.0/build_mingw/mingw-w64 CFLAGS='-I/d/Prog/winlibs64ucrt_stage/custombuilt/include/libdl-win32   -march=nocona -msahf -mtune=generic -O2' CXXFLAGS='-Wno-int-conversion  -march=nocona -msahf -mtune=generic -O2' LDFLAGS='-pthread -Wl,--no-insert-timestamp -Wl,--dynamicbase -Wl,--high-entropy-va -Wl,--nxcompat -Wl,--tsaware' LD=/d/Prog/winlibs64ucrt_stage/custombuilt/share/binutils/bin/ld.exe
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 13.2.0 (MinGW-W64 x86_64-ucrt-posix-seh, built by Brecht Sanders, r5)
```

**Comment by zhangyuang** [comment]
fix in ffi-rs@1.0.96
