### ISSUE TITLE
支持 U32 类型

### ISSUE THREAD

**Issue by mushan0x0** [zhangyuang/node-ffi-rs#81]
## Current ffi-rs version

Print current Node.js info with the following code

```json
{
  "name": "ffi-rs",
  "version": "1.0.98",
  "main": "index.js",
  "types": "index.d.ts",
  "description": "A module written in Rust and N-API provides interface (FFI) features for Node.js",
  "napi": {
    "name": "ffi-rs",
    "triples": {
      "additional": [
        "aarch64-apple-darwin",
        "aarch64-unknown-linux-gnu",
        "aarch64-unknown-linux-musl",
        "arm-unknown-linux-gnueabihf",
        "i686-pc-windows-msvc",
        "x86_64-unknown-linux-musl",
        "aarch64-pc-windows-msvc"
      ]
    }
  },
  "author": "zhangyuang",
  "homepage": "https://github.com/zhangyuang/node-ffi-rs#readme",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/zhangyuang/node-ffi-rs.git"
  },
  "keywords": [
    "ffi",
    "rust",
    "node.js",
    "napi"
  ],
  "files": [
    "index.js",
    "index.d.ts",
    "README.md"
  ],
  "license": "MIT",
  "dependencies": {},
  "devDependencies": {
    "@napi-rs/cli": "^2.15.2",
    "@types/node": "^20.8.7",
    "benny": "^3.7.1",
    "conventional-changelog-cli": "^4.1.0",
    "esno": "^4.0.0",
    "ffi-napi": "^4.0.3",
    "koa": "^2.14.2",
    "shelljs": "^0.8.5",
    "typescript": "^5.4.5"
  },
  "scripts": {
    "artifacts": "napi artifacts",
    "build:c": "node scripts/compile.js",
    "build:dev": "env=development node scripts/build.js",
    "build": "node scripts/build.js",
    "publish:npm": "node scripts/publish.js",
    "test": "esno ./test.ts",
    "changelog": "conventional-changelog -p angular -i CHANGELOG.md -s -r 0 && git add . && git commit -m \"docs: update changelog.md\" && git push origin master",
    "pub": "npm version patch && git push origin master --tags && npm run changelog",
    "pub:alpha": "npm version prerelease --preid=alpha && git push origin master --tags"
  },
  "optionalDependencies": {
    "@yuuang/ffi-rs-darwin-arm64": "1.0.98",
    "@yuuang/ffi-rs-darwin-x64": "1.0.98",
    "@yuuang/ffi-rs-linux-arm-gnueabihf": "1.0.98",
    "@yuuang/ffi-rs-linux-arm64-gnu": "1.0.98",
    "@yuuang/ffi-rs-linux-arm64-musl": "1.0.98",
    "@yuuang/ffi-rs-linux-x64-gnu": "1.0.98",
    "@yuuang/ffi-rs-linux-x64-musl": "1.0.98",
    "@yuuang/ffi-rs-win32-arm64-msvc": "1.0.98",
    "@yuuang/ffi-rs-win32-ia32-msvc": "1.0.98",
    "@yuuang/ffi-rs-win32-x64-msvc": "1.0.98"
  }
}
```

```
ffi-rs-darwin-arm64
```

Print current Node.js info with the following code

```
arm64 darwin
```

## Descibe your problem in detail

我想使用 [CGDisplayBounds](https://developer.apple.com/documentation/coregraphics/1456395-cgdisplaybounds) 在 mac 上获取显示屏大小，但似乎不支持 U32 类型，导致报错：

```
Error
    at wrapLoad (/Users/xxx/Documents/project/xxx/node_modules/ffi-rs/index.js:352:10)
    at getMainDisplaySize (/Users/xxx/Documents/project/xxx/test.js:35:26) {
  code: 'NumberExpected'
}
```

## What's your expect result

希望能够支持 U32 类型，正确获取显示屏大小

## The reproduction repo address

```js
// test.js
const { load, open, DataType } = require("ffi-rs");

// 打开 ApplicationServices 框架
open({
  library: "ApplicationServices",
  path: "/System/Library/Frameworks/ApplicationServices.framework/ApplicationServices",
});

// 定义 CGRect 结构体
const CGRect = {
  origin: {
    x: DataType.Double,
    y: DataType.Double,
  },
  size: {
    width: DataType.Double,
    height: DataType.Double,
  },
};

// 获取主屏幕尺寸的函数
const getMainDisplaySize = async () => {
  // 调用 CGMainDisplayID() 获取主显示器 ID
  const mainDisplayID = await load({
    library: "ApplicationServices",
    funcName: "CGMainDisplayID",
    retType: DataType.I32, // 不支持 U32 ，使用 I32 报错
    freeResultMemory: true,
    errno: true,
    paramsType: [],
    paramsValue: [],
  });

  // 调用 CGDisplayBounds() 获取显示器边界
  const bounds = await load({
    library: "ApplicationServices",
    funcName: "CGDisplayBounds",
    paramsType: [DataType.I32], // 不支持 U32 ，使用 I32 报错
    freeResultMemory: true,
    errno: true,
    paramsValue: [mainDisplayID],
    retType: CGRect,
  });

  return bounds;
};

getMainDisplaySize().then(console.log);

```

**Comment by zhangyuang** [comment]
问题和u32还是i32没有关系，传递的变量类型就不正确。请使用ts来正确的获取变量类型or自行打印每一步的返回值

**Comment by zhangyuang** [comment]
开启errno后返回值为对象类型

**Comment by zhangyuang** [comment]
🤔这个函数返回类型是静态结构体而不是结构体指针类型，处理起来比较复杂。

可以先使用https://developer.apple.com/documentation/coregraphics/1456361-cgdisplaypixelswide这种返回类型简单的函数。

此问题将会在之后的版本进行修复

**Comment by mushan0x0** [comment]
牛👍，没问题了
